from environs import Env

env = Env()
env.read_env()

TWITTER_CONSUMER_KEY = env.str("TWITTER_CONSUMER_KEY")
TWITTER_CONSUMER_SECRET = env.str("TWITTER_CONSUMER_SECRET")
TWITTER_ACCESS_TOKEN = env.str("TWITTER_ACCESS_TOKEN")
TWITTER_ACCESS_TOKEN_SECRET = env.str("TWITTER_ACCESS_TOKEN_SECRET")
